auth:
  db:
    prisma:
      migrate:
        enabled: true

todo:
  db:
    prisma:
      migrate:
        enabled: true

user:
  db:
    prisma:
      migrate:
        enabled: true
      seed:
        enabled: true

nats:
  host: nats.dev.svc.cluster.local
