version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/auth"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/todo"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/user"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/web-client"
    target-branch: "dependabot/update"
    schedule:
      interval: "monthly"
