version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/auth"
    target-branch: "dependabot/update"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/todo"
    target-branch: "dependabot/update"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/user"
    target-branch: "dependabot/update"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/web-client"
    target-branch: "dependabot/update"
    schedule:
      interval: "daily"
