FROM node:18.4.0 as builder
WORKDIR /app
COPY .env .
COPY package*.json ./
COPY prisma .
RUN npm install
COPY . .
RUN npm run build

FROM node:18.4.0-alpine as prod
WORKDIR /app
ENV NODE_ENV=production
COPY .env .
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist .
COPY --from=builder /app/node_modules/.prisma node_modules/
CMD [ "npm", "run", "start:prod" ]
