FROM node:18.4.0 AS deps
WORKDIR /app
COPY .env package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

FROM node:18.4.0 AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
CMD [ "npm", "run", "start:prod" ]
