dockerCredentials:
  username: ENC[AES256_GCM,data:Crs/JWFaLbkO,iv:lQnBLHvm0Uhw93EMzukipPb9BWjr6iFsKBM2AR0b4w8=,tag:RiP7sgo+S+4JySHfWAYgXg==,type:str]
  password: ENC[AES256_GCM,data:7/bKgb8786DyQqDfXFNcpD4M0sSu/sPrwkAGZX9gYW/ZYEew,iv:Xga4mQrJW5VGWoBMRPgEyAUm+GIDG5tP6oYxBzvm7gY=,tag:tKdz8pIB3uhwlhw2syaxyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-11-21T21:10:33Z"
  mac: ENC[AES256_GCM,data:e1czQt8/8NY/MTgn708exuVoWRpzMkOHxMIuynnkLIq2/wuCxmleV3ezlT6qCAjUPTCvzCrY8Q17AiJKD0FbTh6WuQvLaZgXcea+/RjjKSMk/JLXegG9K89TwV9k3sWeX9TMGjffbEKb4xdBKxmSA+2GYiM0c7vUF1Z2HATUh2Q=,iv:ubnwO/PSTLXh/sJyll4sXZ6DcvykwGOiLwRJJqsFLYA=,tag:v0Y7/4r/LVpukR6a55iqNA==,type:str]
  pgp:
    - created_at: "2022-11-21T21:10:32Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA6MC6hSUWL6lAQv/cXZJnRQH2GkWFQOtc4JczymTegLUWEU/snVXd2A7EQc5
        8YoDVvfHzUl1048wAxR34XNHfdHLzBigPVpoaGlwqxXovyNo4dxIC5prdynRD2N1
        uBLVyITvywR6gk8r3/C4HzMXFcEcDYV0EPjlvvW82BZ/tEHjMyDdBdVL/cLXTPax
        ZpSqdkFmw1G/GoU7ckcWx6p0segadGfoK6a2AIaD6rKRqmSwEgAlPlw8Gd+czFAG
        e62m7f+YGrRwD7GgEb0IUqalNJiBpfJxZTFE6z5qLl+yl+I+QxU7fb09tp7KkQ6t
        Oj1wC+kdKo7ibUmFozs+0bNMhP2lrTjUAd+QG9MqWZI8kqMYNjM/VEFcfo87zhHw
        A8ztylrZJHBzXGCL6V6+3y0uIxBmOaXj86Z3d6oMYfeRFsePGxed6qlIepX75afT
        AHOUu7FLu5QytY0zNNuow7ygfOhserkJ3YGIm/emTHzdNucIps6thLyyJsr+AFu0
        CeTOzezqrjEngQ5Mcn3B0l4BibrGGJU8tXitrEzYbwqO6RchLXbV1x/Q2NHduADR
        cU2vfr+r+VEk5WnDeszgfDo+Twc9mGmD0a5f8R7c5WTGIaPBKAvho3D4Tyk0gr9d
        vhuf5qOunpYbCsbW2lMc
        =zI9n
        -----END PGP MESSAGE-----
      fp: 5F94D9434B8F3CC4D21331AEE075EED1D69F70BD
    - created_at: "2022-11-21T21:10:32Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DUoX+pDYmouoSAQdAqC5qISDape2PHxtovGT38l2MfrtgiJSxrtPd4a1gVSkw
        9yb1vkixX9MhWi+sUMwIIHfvlQ4nJvaH6ojsBv5yp2LDVTcAooT4DZ3EiDK2vDrd
        0l4BaS+buvRIZfc/QtjdHNxYm0G2TQR6WPHT6Aj3VVGGqlmTFiZ63kx4R+V5UiDp
        fe2GxxkrcTqfJSj6Pg0gBYMrlyFGEfH8AqKL8v0CEVulg+BN90uFM1tFDcyTU/oT
        =q+h6
        -----END PGP MESSAGE-----
      fp: 8617E6C8E5E2EB912C3FB0176FD58CAE7EEB5C66
  unencrypted_suffix: _unencrypted
  version: 3.7.3
