apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: auth
      context: auth
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
        cacheFrom: [auth]
    - image: todo
      context: todo
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
        cacheFrom: [todo]
    - image: user
      context: user
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
        cacheFrom: [user]
    - image: web-client
      context: web-client
      sync:
        infer:
          - src/**/*.{ts,tsx}
      docker:
        dockerfile: .k8s/docker/nextjs/Dockerfile.dev
        cacheFrom: [web-client]
  local:
    useBuildkit: true
    push: false
  tagPolicy:
    inputDigest: {}
test:
  - image: auth
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: todo
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: user
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: web-client
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
manifests:
  helm:
    releases:
      - &certManagerRelease
        name: cert-manager
        remoteChart: cert-manager
        valuesFiles:
          - .k8s/values/main/cert-manager.yaml
          - .k8s/values/dev/cert-manager.yaml
        namespace: cert-manager
        version: 1.10.0
        createNamespace: true
        repo: https://charts.jetstack.io
      - &configRelease
        name: config
        chartPath: .k8s/helm-charts/config
        valuesFiles:
          - .k8s/values/main/config.yaml
          - .k8s/values/dev/config.yaml
        namespace: dev
        createNamespace: true
        wait: true
      - &ingressNginxRelease
        name: ingress-nginx
        remoteChart: ingress-nginx
        valuesFiles:
          - .k8s/values/main/ingress-nginx.yaml
          - .k8s/values/dev/ingress-nginx.yaml
        namespace: dev
        version: 4.2.5
        repo: https://kubernetes.github.io/ingress-nginx
      - &natsRelease
        name: nats
        remoteChart: nats
        valuesFiles:
          - .k8s/values/main/nats.yaml
          - .k8s/values/dev/nats.yaml
        namespace: dev
        version: 0.18.0
        wait: true
        repo: https://nats-io.github.io/k8s/helm/charts/
      - &dbAuthRelease
        name: db-auth
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/auth.yaml
          - .k8s/values/dev/db/base.yaml
          - .k8s/values/dev/db/auth.yaml
        namespace: dev
        version: 9.2.1
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - &dbTodoRelease
        name: db-todo
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/todo.yaml
          - .k8s/values/dev/db/base.yaml
          - .k8s/values/dev/db/todo.yaml
        namespace: dev
        version: 9.2.1
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - &dbUserRelease
        name: db-user
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/user.yaml
          - .k8s/values/dev/db/base.yaml
          - .k8s/values/dev/db/user.yaml
        namespace: dev
        version: 9.2.1
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - &appAuthRelease
        name: app-auth
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/auth.yaml
          - .k8s/values/dev/app/base.yaml
          - .k8s/values/dev/app/auth.yaml
        namespace: dev
      - &appTodoRelease
        name: app-todo
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/todo.yaml
          - .k8s/values/dev/app/base.yaml
          - .k8s/values/dev/app/todo.yaml
        namespace: dev
      - &appUserRelease
        name: app-user
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/user.yaml
          - .k8s/values/dev/app/base.yaml
          - .k8s/values/dev/app/user.yaml
        namespace: dev
      - &appWebClientRelease
        name: app-web-client
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/web-client.yaml
          - .k8s/values/dev/app/base.yaml
          - .k8s/values/dev/app/web-client.yaml
        namespace: dev
deploy:
  helm: {}
  logs:
    prefix: auto
portForward:
  - resourceType: service
    resourceName: ingress-nginx-dev-controller
    namespace: dev
    port: 443
    address: 0.0.0.0
    localPort: 3443
  - resourceType: service
    resourceName: ingress-nginx-dev-controller
    namespace: dev
    port: 80
    address: 0.0.0.0
    localPort: 3000
profiles:
  - name: dev
  - name: ci
    patches:
      # Build Artifacts (replacing dockerfiles)
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      - op: replace
        path: /build/artifacts/3/docker/dockerfile
        value: .k8s/docker/nextjs/Dockerfile.ci
  - name: prod
    patches:
      # Build Artifacts (replacing dockerfiles)
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      - op: replace
        path: /build/artifacts/3/docker/dockerfile
        value: .k8s/docker/nextjs/Dockerfile.prod
    build:
      local:
        useBuildkit: true
        push: true
    manifests:
      helm:
        releases:
          - <<: *certManagerRelease
            valuesFiles:
              - .k8s/values/main/cert-manager.yaml
              - .k8s/values/prod/cert-manager.yaml
            useHelmSecrets: true
          - <<: *configRelease
            valuesFiles:
              - .k8s/values/main/config.yaml
              - .k8s/values/prod/config.yaml
              - .k8s/secrets/prod/config.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *ingressNginxRelease
            valuesFiles:
              - .k8s/values/main/ingress-nginx.yaml
              - .k8s/values/prod/ingress-nginx.yaml
            namespace: prod
            useHelmSecrets: true
          - name: external-dns
            remoteChart: external-dns
            valuesFiles:
              - .k8s/values/prod/external-dns.yaml
              - .k8s/secrets/prod/external-dns.yaml
            namespace: prod
            version: 6.12.0
            useHelmSecrets: true
            repo: https://charts.bitnami.com/bitnami
          - <<: *natsRelease
            valuesFiles:
              - .k8s/values/main/nats.yaml
              - .k8s/values/prod/nats.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *dbAuthRelease
            valuesFiles:
              - .k8s/values/main/db/base.yaml
              - .k8s/values/main/db/auth.yaml
              - .k8s/values/prod/db/base.yaml
              - .k8s/values/prod/db/auth.yaml
              - .k8s/secrets/prod/db/auth.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *dbTodoRelease
            valuesFiles:
              - .k8s/values/main/db/base.yaml
              - .k8s/values/main/db/todo.yaml
              - .k8s/values/prod/db/base.yaml
              - .k8s/values/prod/db/todo.yaml
              - .k8s/secrets/prod/db/todo.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *dbUserRelease
            valuesFiles:
              - .k8s/values/main/db/base.yaml
              - .k8s/values/main/db/user.yaml
              - .k8s/values/prod/db/base.yaml
              - .k8s/values/prod/db/user.yaml
              - .k8s/secrets/prod/db/user.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *appAuthRelease
            valuesFiles:
              - .k8s/values/main/app/base.yaml
              - .k8s/values/main/app/auth.yaml
              - .k8s/values/prod/app/base.yaml
              - .k8s/values/prod/app/auth.yaml
              - .k8s/secrets/prod/app/auth.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *appTodoRelease
            valuesFiles:
              - .k8s/values/main/app/base.yaml
              - .k8s/values/main/app/todo.yaml
              - .k8s/values/prod/app/base.yaml
              - .k8s/values/prod/app/todo.yaml
              - .k8s/secrets/prod/app/todo.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *appUserRelease
            valuesFiles:
              - .k8s/values/main/app/base.yaml
              - .k8s/values/main/app/user.yaml
              - .k8s/values/prod/app/base.yaml
              - .k8s/values/prod/app/user.yaml
              - .k8s/secrets/prod/app/user.yaml
            namespace: prod
            useHelmSecrets: true
          - <<: *appWebClientRelease
            valuesFiles:
              - .k8s/values/main/app/base.yaml
              - .k8s/values/main/app/web-client.yaml
              - .k8s/values/prod/app/base.yaml
              - .k8s/values/prod/app/web-client.yaml
            namespace: prod
            useHelmSecrets: true
