apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: todo-app
build:
  local:
    concurrency: 1
    useBuildkit: true
  artifacts:
    - image: gcr.io/k8s-full-stack-starter/web-client
      context: web-client
      custom:
        dependencies:
          paths:
            - ../.k8s/docker/nextjs/*
            - ./**/*
        buildCommand: |
          docker build . --tag=$IMAGE --file=../.k8s/docker/nextjs/Dockerfile.$ENV
      sync:
        manual:
          - src: "src/**/*.{ts,tsx}"
            dest: .

deploy:
  logs:
    prefix: auto
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        version: 4.2.1
        namespace: ingress-nginx
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/ingress-nginx-values.yaml

      - name: nats
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
        version: 0.17.3
        namespace: dev
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/nats-values.yaml
        wait: true

      - name: dev-db
        useHelmSecrets: true
        chartPath: .k8s/helm-charts/db
        namespace: dev
        createNamespace: true
        valuesFiles:
          - .k8s/values/dev/db-values.yaml
          - .k8s/values/dev/db-secrets.yaml
        wait: true

      - name: dev-app
        useHelmSecrets: true
        chartPath: .k8s/helm-charts/app
        namespace: dev
        createNamespace: true
        artifactOverrides:
          webClient:
            image: gcr.io/k8s-full-stack-starter/web-client
        imageStrategy:
          helm:
            explicitRegistry: true
        valuesFiles:
          - .k8s/values/dev/app-values.yaml
          - .k8s/values/dev/app-secrets.yaml

test:
  - image: gcr.io/k8s-full-stack-starter/web-client
    custom:
     - command: echo 'yea'
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
