apiVersion: skaffold/v3
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: auth
      context: auth
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: ../.k8s/docker/nestjs/Dockerfile.dev
    - image: todo
      context: todo
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: ../.k8s/docker/nestjs/Dockerfile.dev
    - image: user
      context: user
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: ../.k8s/docker/nestjs/Dockerfile.dev
    - image: web-client
      context: web-client
      sync:
        infer:
          - src/**/*.{ts,tsx}
      docker:
        dockerfile: ../.k8s/docker/nextjs/Dockerfile.dev
  local:
    useBuildkit: true
    concurrency: 1
manifests:
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        valuesFiles:
          - .k8s/values/dev/ingress-nginx-values.yaml
        namespace: ingress-nginx
        version: 4.2.5
        createNamespace: true
        wait: true
        repo: https://kubernetes.github.io/ingress-nginx
        upgradeOnChange: true
      - name: nats
        remoteChart: nats
        valuesFiles:
          - .k8s/values/dev/nats-values.yaml
        namespace: dev
        version: 0.18.0
        createNamespace: true
        wait: true
        repo: https://nats-io.github.io/k8s/helm/charts/
        upgradeOnChange: true
      - name: db
        chartPath: .k8s/helm-charts/db
        valuesFiles:
          - .k8s/values/dev/db-values.yaml
          - .k8s/values/dev/db-secrets.yaml
        namespace: dev
        createNamespace: true
        wait: true
        useHelmSecrets: true
      - name: app
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/dev/app-values.yaml
          - .k8s/values/dev/app-secrets.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
deploy:
  helm: {}
  logs:
    prefix: auto
test:
  - image: auth
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: todo
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: user
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: web-client
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    address: 0.0.0.0
    localPort: 3000
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
