apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: todo-app
build:
  local:
    concurrency: 3
    useBuildkit: true
  artifacts:
    - image: gcr.io/k8s-full-stack-starter/auth
      context: auth
      custom: &nestjsCustomBuild
        dependencies:
          paths:
            - ../.k8s/docker/nestjs/*
            - ./**/*
        buildCommand: |
          docker build . --tag=$IMAGE --file=../.k8s/docker/nestjs/Dockerfile.$PROFILE
      sync: &nestjsSync
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gcr.io/k8s-full-stack-starter/todo
      context: todo
      custom: *nestjsCustomBuild
      sync: *nestjsSync
    - image: gcr.io/k8s-full-stack-starter/user
      context: user
      custom: *nestjsCustomBuild
      sync: *nestjsSync
    - image: gcr.io/k8s-full-stack-starter/web-client
      context: web-client
      custom:
        dependencies:
          paths:
            - ../.k8s/docker/nextjs/*
            - ./**/*
        buildCommand: |
          docker build . --tag=$IMAGE --file=../.k8s/docker/nextjs/Dockerfile.$PROFILE
      sync:
        manual:
          - src: "src/**/*.{ts,tsx}"
            dest: .
    - image: gcr.io/k8s-full-stack-starter/auth-prisma
      context: auth
      docker:
        dockerfile: .k8s/docker/Dockerfile.prisma
    - image: gcr.io/k8s-full-stack-starter/todo-prisma
      context: todo
      docker:
        dockerfile: .k8s/docker/Dockerfile.prisma
    - image: gcr.io/k8s-full-stack-starter/user-prisma
      context: user
      docker:
        dockerfile: .k8s/docker/Dockerfile.prisma

deploy:
  logs:
    prefix: auto
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        version: 4.2.1
        namespace: ingress-nginx
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/ingress-nginx-values.yaml

      - name: nats
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
        version: 0.17.3
        namespace: dev
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/nats-values.yaml
        wait: true

      - name: dev-db
        useHelmSecrets: true
        chartPath: .k8s/helm-charts/db
        namespace: dev
        createNamespace: true
        valuesFiles:
          - .k8s/values/dev/db-values.yaml
          - .k8s/values/dev/db-secrets.yaml
        wait: true

      - name: dev-app
        useHelmSecrets: true
        chartPath: .k8s/helm-charts/app
        namespace: dev
        createNamespace: true
        artifactOverrides:
          auth:
            image: gcr.io/k8s-full-stack-starter/auth
            db.prisma.image: gcr.io/k8s-full-stack-starter/auth-prisma
          todo:
            image: gcr.io/k8s-full-stack-starter/todo
            db.prisma.image: gcr.io/k8s-full-stack-starter/todo-prisma
          user:
            image: gcr.io/k8s-full-stack-starter/user
            db.prisma.image: gcr.io/k8s-full-stack-starter/user-prisma
          webClient:
            image: gcr.io/k8s-full-stack-starter/web-client
        imageStrategy:
          helm:
            explicitRegistry: true
        valuesFiles:
          - .k8s/values/dev/app-values.yaml
          - .k8s/values/dev/app-secrets.yaml

test:
  - image: gcr.io/k8s-full-stack-starter/auth
    custom: &npmTestCommand
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: gcr.io/k8s-full-stack-starter/todo
    custom: *npmTestCommand
  - image: gcr.io/k8s-full-stack-starter/user
    custom: *npmTestCommand
  - image: gcr.io/k8s-full-stack-starter/web-client
    custom: *npmTestCommand

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
