apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: gcr.io/k8s-full-stack-starter/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gcr.io/k8s-full-stack-starter/todo-item
      context: todo-item
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/k8s-full-stack-starter/todo-list
      context: todo-list
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/k8s-full-stack-starter/user
      context: user
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gcr.io/k8s-full-stack-starter/web-client
      context: web-client
      docker:
        dockerfile: Dockerfile

deploy:
  logs:
    prefix: auto
  helm:
    releases:
      - name: kong
        remoteChart: kong
        repo: https://charts.konghq.com
        version: 2.11.0
        namespace: kong
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/kong-values.yaml

      - name: nats
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
        version: 0.17.3
        namespace: dev
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - .k8s/values/dev/nats-values.yaml
        wait: true

      - name: dev
        useHelmSecrets: true
        chartPath: .k8s/helm-charts
        namespace: dev
        createNamespace: true
        artifactOverrides:
          auth:
            main:
              image: gcr.io/k8s-full-stack-starter/auth
          todoItem:
            main:
              image: gcr.io/k8s-full-stack-starter/todo-item
          todoList:
            main:
              image: gcr.io/k8s-full-stack-starter/todo-list
          user:
            main:
              image: gcr.io/k8s-full-stack-starter/user
          webClient:
            main:
              image: gcr.io/k8s-full-stack-starter/web-client
        imageStrategy:
          helm:
            explicitRegistry: true
        valuesFiles:
          - .k8s/values/dev/values.yaml
          - .k8s/values/dev/secrets.yaml

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
