apiVersion: skaffold/v3
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: auth
      context: auth
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: todo
      context: todo
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: user
      context: user
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: web-client
      context: web-client
      sync:
        infer:
          - src/**/*.{ts,tsx}
      docker:
        dockerfile: .k8s/docker/nextjs/Dockerfile.dev
  local:
    useBuildkit: true
    concurrency: 1
test:
  - image: auth
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: todo
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: user
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: web-client
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
manifests:
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        valuesFiles:
          - .k8s/values/main/ingress-nginx.yaml
        namespace: dev
        version: 4.2.5
        createNamespace: true
        repo: https://kubernetes.github.io/ingress-nginx
      - name: nats
        remoteChart: nats
        valuesFiles:
          - .k8s/values/main/nats.yaml
        namespace: dev
        version: 0.18.0
        createNamespace: true
        wait: true
        repo: https://nats-io.github.io/k8s/helm/charts/
      - name: config
        chartPath: .k8s/helm-charts/config
        valuesFiles:
          - .k8s/values/main/config.yaml
        namespace: dev
        createNamespace: true
        wait: true
        useHelmSecrets: true
      - name: db-auth
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/auth.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: db-todo
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/todo.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: db-user
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/user.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: app-auth
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/auth.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-todo
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/todo.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-user
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/user.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-web-client
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/web-client.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
deploy:
  helm: {}
  logs:
    prefix: auto
profiles:
  - name: dev
    patches:
      # Helm Releases (adding .k8s/values/dev files)
      # ingress-nginx
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: .k8s/values/dev/ingress-nginx.yaml
      # nats
      - op: add
        path: /manifests/helm/releases/1/valuesFiles/-
        value: .k8s/values/dev/nats.yaml
      # config
      - op: add
        path: /manifests/helm/releases/2/valuesFiles/-
        value: .k8s/values/dev/config.yaml
      # db-auth
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/dev/db/auth.yaml
      # db-todo
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/dev/db/todo.yaml
      # db-user
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/dev/db/user.yaml
      # app-auth
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/dev/app/auth.yaml
      # app-todo
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/dev/app/todo.yaml
      # app-user
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/dev/app/user.yaml
      # app-web-client
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/dev/app/web-client.yaml
    portForward:
      - resourceType: service
        resourceName: ingress-nginx-dev-controller
        namespace: dev
        port: 80
        address: 0.0.0.0
        localPort: 3000
  - name: ci
    patches:
      # Build Artifacts (replacing dockerfiles)
      # auth
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      # todo
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      # user
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.ci
      # web-client
      - op: replace
        path: /build/artifacts/3/docker/dockerfile
        value: .k8s/docker/nextjs/Dockerfile.ci
  - name: prod
    patches:
      # Build Artifacts (replacing dockerfiles)
      # auth
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      # todo
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      # user
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: .k8s/docker/nestjs/Dockerfile.prod
      # web-client
      - op: replace
        path: /build/artifacts/3/docker/dockerfile
        value: .k8s/docker/nextjs/Dockerfile.prod
      # Helm Releases (adding .k8s/values/prod files)
      # ingress-nginx
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: .k8s/values/prod/ingress-nginx.yaml
      # nats
      - op: add
        path: /manifests/helm/releases/1/valuesFiles/-
        value: .k8s/values/prod/nats.yaml
      # config
      - op: add
        path: /manifests/helm/releases/2/valuesFiles/-
        value: .k8s/values/prod/config.yaml
      # db-auth
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/prod/db/base.yaml
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/prod/db/auth.yaml
      # db-todo
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/prod/db/base.yaml
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/prod/db/todo.yaml
      # db-user
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/prod/db/base.yaml
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/prod/db/user.yaml
      # app-auth
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/prod/app/base.yaml
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/prod/app/auth.yaml
      # app-todo
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/prod/app/base.yaml
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/prod/app/todo.yaml
      # app-user
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/prod/app/base.yaml
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/prod/app/user.yaml
      # app-web-client
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/prod/app/base.yaml
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/prod/app/web-client.yaml
      # Helm Releases (changing namespace to prod)
      - op: replace
        path: /manifests/helm/releases/0/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/1/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/2/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/3/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/4/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/5/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/6/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/7/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/8/namespace
        value: prod
      - op: replace
        path: /manifests/helm/releases/9/namespace
        value: prod
    portForward:
      - resourceType: service
        resourceName: ingress-nginx-prod-controller
        namespace: prod
        port: 80
        address: 0.0.0.0
        localPort: 3100
