apiVersion: skaffold/v3
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: auth
      context: auth
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: todo
      context: todo
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: user
      context: user
      sync:
        infer:
          - src/**/*.ts
      docker:
        dockerfile: .k8s/docker/nestjs/Dockerfile.dev
    - image: web-client
      context: web-client
      sync:
        infer:
          - src/**/*.{ts,tsx}
      docker:
        dockerfile: .k8s/docker/nextjs/Dockerfile.dev
  local:
    useBuildkit: true
    concurrency: 1
manifests:
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        valuesFiles:
          - .k8s/values/main/ingress-nginx.yaml
        namespace: ingress-nginx
        version: 4.2.5
        createNamespace: true
        wait: true
        repo: https://kubernetes.github.io/ingress-nginx
      - name: nats
        remoteChart: nats
        valuesFiles:
          - .k8s/values/main/nats.yaml
        namespace: dev
        version: 0.18.0
        createNamespace: true
        wait: true
        repo: https://nats-io.github.io/k8s/helm/charts/
      - name: config
        chartPath: .k8s/helm-charts/config
        valuesFiles:
          - .k8s/values/main/config.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
        wait: true
      - name: db-auth
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/auth.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: db-todo
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/todo.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: db-user
        remoteChart: mysql
        valuesFiles:
          - .k8s/values/main/db/base.yaml
          - .k8s/values/main/db/user.yaml
        namespace: dev
        version: 9.2.1
        createNamespace: true
        wait: true
        repo: https://charts.bitnami.com/bitnami
      - name: app-auth
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/auth.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-todo
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/todo.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-user
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/user.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
      - name: app-web-client
        chartPath: .k8s/helm-charts/app
        valuesFiles:
          - .k8s/values/main/app/base.yaml
          - .k8s/values/main/app/web-client.yaml
        namespace: dev
        createNamespace: true
        useHelmSecrets: true
deploy:
  helm: {}
  logs:
    prefix: auto
test:
  - image: auth
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: todo
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: user
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
  - image: web-client
    custom:
      - command: docker run --entrypoint '/bin/sh' $IMAGE -c 'npm run test'
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    address: 0.0.0.0
    localPort: 3000
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    patches:
      # Helm Releases (adding .k8s/values/dev files)
      # ingress-nginx
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: .k8s/values/dev/ingress-nginx.yaml
      # nats
      - op: add
        path: /manifests/helm/releases/1/valuesFiles/-
        value: .k8s/values/dev/nats.yaml
      # config
      - op: add
        path: /manifests/helm/releases/2/valuesFiles/-
        value: .k8s/values/dev/config.yaml
      # db-auth
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/3/valuesFiles/-
        value: .k8s/values/dev/db/auth.yaml
      # db-todo
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/4/valuesFiles/-
        value: .k8s/values/dev/db/todo.yaml
      # db-user
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/dev/db/base.yaml
      - op: add
        path: /manifests/helm/releases/5/valuesFiles/-
        value: .k8s/values/dev/db/user.yaml
      # app-auth
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/6/valuesFiles/-
        value: .k8s/values/dev/app/auth.yaml
      # app-todo
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/7/valuesFiles/-
        value: .k8s/values/dev/app/todo.yaml
      # app-user
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/8/valuesFiles/-
        value: .k8s/values/dev/app/user.yaml
      # app-web-client
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/dev/app/base.yaml
      - op: add
        path: /manifests/helm/releases/9/valuesFiles/-
        value: .k8s/values/dev/app/user.yaml
