{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
{{ include "main.secret.content" . }}
{{- end -}}
