apiVersion: v2
name: app
description: Helm chart for releasing any image (modified bitnami/node)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
