default: &default
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    clusterIP: None

auth:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  ingress:
    enabled: false
  service: {}

todo:
  <<: *default
  nameOverride: todo
  containerPorts:
    http: 3002
  ingress:
    path: /api/todo(/|$)(.*)

user:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  containerPorts:
    http: 3001
  ingress:
    path: /api/user(/|$)(.*)

webClient:
  <<: *default
  nameOverride: web-client
  containerPorts:
    http: 8080
  ingress:
    rewriteTarget: /$1
    path: /(.*)

nats:
  host: nats
  port: 4222
