default: &default
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    clusterIP: None

ingress: &ingress
  rewriteTarget: /$2
  auth:
    enabled: true
    responseHeaders: X-User-ID
    convertHeaders:
      - from: X-Set-Cookie-jwt
        to: Set-Cookie
      - from: X-Set-Cookie-refresh-token
        to: Set-Cookie

auth:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  ingress:
    enabled: false
  service: {}

todo:
  <<: *default
  nameOverride: todo
  containerPorts:
    http: 3002
  ingress:
    <<: *ingress
    path: /api/todo(/|$)(.*)

user:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  containerPorts:
    http: 3001
  ingress:
    <<: *ingress
    path: /api/user(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~ ^/api/user/auth/?$ {
          internal;
        }
  service: {}

webClient:
  <<: *default
  nameOverride: web-client
  containerPorts:
    http: 8080
  ingress:
    <<: *ingress
    rewriteTarget: /$1
    path: /(.*)

nats:
  host: nats
  port: 4222
