default: &default
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  ingress: &ingress
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    pathType: Prefix
  service: &service
    clusterIP: None

auth:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  ingress:
    enabled: false
  service: {}

todo:
  <<: *default
  nameOverride: todo
  containerPorts:
    http: 3002
  ingress:
    <<: *ingress
    path: /api/todo(/|$)(.*)

user:
  <<: *default
  extraEnvFrom:
    - configMapRef:
        name: nats
  containerPorts:
    http: 3001
  ingress:
    <<: *ingress
    path: /api/user(/|$)(.*)

webClient:
  <<: *default
  nameOverride: web-client
  containerPorts:
    http: 8080
  ingress:
    <<: *ingress
    path: (/|$)(.*)

nats:
  host: nats
  port: 4222
