{{- if .Values.db.enabled -}}
{{- if .Values.db.prisma.migrate.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-db-migrate
  namespace: {{ include "common.names.namespace" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: {{ include "main.db.prisma.image" . }}
          envFrom:
            - secretRef:
                name: {{ include "common.names.fullname" . }}-preinst
          command:
            - /bin/sh
            - -c
            - npx prisma migrate deploy
{{- end }}
---
{{ if .Values.db.prisma.seed.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-db-seed
  namespace: {{ include "common.names.namespace" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-seed
          image: {{ include "main.db.prisma.image" . }}
          envFrom:
            - secretRef:
                name: {{ include "common.names.fullname" . }}-preinst
          command:
            - /bin/sh
            - -c
            - npx ts-node prisma/{{ .Values.db.prisma.seed.fileName }}
{{- end -}}
{{- end -}}
