{{- if .Values.db.enabled -}}
{{- if or .Values.db.prisma.migrate.enabled .Values.db.prisma.seed.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-preinst
  namespace: {{ include "common.names.namespace" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
{{ include "main.secret.content" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
{{ include "main.secret.content" . }}
{{- end -}}
