export const QUERY_KEY = {
  AUTH: 'AUTH',
  TODO: 'TODO',
  TODO_LISTS: 'TODO_LISTS',
  TODO_LIST: 'TODO_LIST',
} as const

export const MUTATION_KEY = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REGISTER: 'REGISTER',
}
