{{ if .Values.node.enabled }}
{{- $namespace := include "common.names.namespace" .Subcharts.node -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" .Subcharts.node }}-env
  namespace: {{ $namespace | quote }}
  labels: {{ include "common.labels.standard" .Subcharts.node | nindent 4 }}
type: Opaque
data:
  {{ if .Values.mysql.enabled }}
  {{- $mysqlServiceName := include "mysql.primary.fullname" .Subcharts.mysql -}}
  DB_HOST: {{ printf "%s.%s.svc.cluster.local" $mysqlServiceName $namespace | b64enc | quote }}
  DB_PORT: {{ .Values.mysql.primary.service.ports.mysql | toString | b64enc | quote }}
  DB_USER: {{ .Values.mysql.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  DB_DATABASE: {{ .Values.mysql.auth.database | b64enc | quote }}
  {{ else if .Values.externalDb.enabled }}
  DB_HOST: {{ .Values.externalDb.host | b64enc | quote }}
  DB_PORT: {{ .Values.externalDb.port | toString | b64enc | quote }}
  DB_USER: {{ .Values.externalDb.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.externalDb.password | b64enc | quote }}
  DB_DATABASE: {{ .Values.externalDb.database | b64enc | quote }}
  {{ end }}
{{ end }}
