{{- if .Values.githubActionsCD -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-cd
  labels: {{- include "config.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: github-actions-cd
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}
