{{- if .Values.githubActionsCD -}}
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-cd
  labels: {{- include "config.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/service-account.name: github-actions-cd
type: kubernetes.io/service-account-token
{{- end -}}
