{{- if .Values.githubActionsCD -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-cd
  labels: {{- include "config.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
automountServiceAccountToken: false
{{- end -}}
