{{- if .Values.dockerCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerCredentials.secretName }}
  labels: {{- include "config.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.dockerCredentials.server (printf "%s:%s" .Values.dockerCredentials.username .Values.dockerCredentials.password | b64enc) | b64enc | quote }}
{{- end -}}
