mysql:
  enabled: false
  createShadowDb: false
  initdbScripts: |
    {{- if .Values.createShadowDb -}}
    create_shadow_db.sql: |
      CREATE DATABASE IF NOT EXISTS shadow_db;
      GRANT ALL PRIVILEGES ON shadow_db.* TO '{{ .Values.auth.username }}'@'%';
    {{- end -}}

main:
  enabled: true
  dbSecretRef:
    name: '{{ include "common.names.fullname" . }}'
    optional: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  ingress:
    ingressClassName: kong
    annotations:
      konghq.com/strip-path: "true"
    pathType: Prefix
  service:
    clusterIP: None

externalDb:
  enabled: false
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""
