FROM node:18.12.1 AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:18.12.1 AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
CMD [ "npm", "run", "start" ]
