FROM node:18.12.1 AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:18.12.1 AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
CMD [ "npm", "run", "dev" ]

# Build on CI to catch potentials errors ignored by `dev`
FROM dev as ci
RUN npm run build
