nameOverride: prod # until https://github.com/kubernetes/ingress-nginx/issues/8936 is fixed
controller:
  ingressClassResource:
    name: nginx-prod
    # Set as default because of cert-manager not setting ingressClassName field
    # Remove when https://github.com/cert-manager/cert-manager/issues/4821 is fixed
    default: true
    controllerValue: k8s.io/ingress-nginx-prod
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: todo.alidrizi.com
      external-dns.alpha.kubernetes.io/ttl: 5m
  resources:
    requests:
      cpu: 50m
      memory: 90Mi
    limits:
      cpu: 50m
      memory: 90Mi
