nameOverride: prod # until https://github.com/kubernetes/ingress-nginx/issues/8936 is fixed
controller:
  scope:
    enabled: true
  ingressClass: nginx-prod
  ingressClassResource:
    name: nginx-prod
    controllerValue: k8s.io/ingress-nginx-prod
