apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-client-service
                port:
                  number: 80
          - path: /api/todo-item
            pathType: Prefix
            backend:
              service:
                name: todo-item-service
                port:
                  number: 3000
          - path: /api/todo-list
            pathType: Prefix
            backend:
              service:
                name: todo-list-service
                port:
                  number: 3000
