#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

echo "Running pre-commit hook"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

echo "CHECKING ${green}/auth${reset}"
cd ./auth && npx lint-staged && cd ..

echo "CHECKING ${green}/todo${reset}"
cd ./todo && npx lint-staged && cd ..

echo "CHECKING ${green}/user${reset}"
cd ./user && npx lint-staged && cd ..

echo "CHECKING ${green}/web-client${reset}"
cd ./web-client && npx lint-staged && cd ..
