name: CI/CD

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@1.7.0

      - name: Setup Helm
        uses: hiberbee/github-action-helm@1.13.0

      - name: Setup Helm Repos
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Setup Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.0.2/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Build
        run: npm run ci:build

      - name: Test
        run: npm run ci:test

      - name: Deploy to Minikube
        run: npm run ci:deploy

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: .scripts/install-deps.sh

      - name: Lint
        run: .scripts/lint.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs:
      - test
      - lint
    env:
      DOCKER_REGISTRY: docker.io/aliidrizi
    steps:
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_SERVER_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_TOKEN }}

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: hiberbee/github-action-helm@1.13.0

      - name: Setup Helm Repos
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Setup Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.0.2/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup SOPS
        uses: mdgreenwald/mozilla-sops-action@v1.2.0
        with:
          version: "3.7.3"

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build
        run: npm run prod:build

      - name: Deploy
        run: npm run prod:deploy
